// "use client";
// // context
// import { styled } from "@mui/material/styles";
// import { HEADER } from "@/src/config";

// import Sidebar from "./components/sidebar";

// scroll bar
import "simplebar-react/dist/simplebar.min.css";

// ----------------------------------------------------------------------
// const MainStayled = styled("main")(({ theme }) => ({
//   // backgroundColor: alpha(
//   //   theme.palette.primary.main,
//   //   theme.palette.action.selectedOpacity
//   // ),
// }));
// ----------------------------------------------------------------------

// const ContainerStyled = styled("div", {
//   shouldForwardProp: (prop) => prop !== "collapseClick",
// })(({ theme }) => ({
//   [theme.breakpoints.up("lg")]: {
//     transition: theme.transitions.create("margin-right", {
//       duration: theme.transitions.duration.shorter,
//     }),
//     // marginRight: SIDEBAR.BASE_WIDTH,
//   },
// }));

// ----------------------------------------------------------------------
// async function getData({ shopStringId }: { shopStringId: string }) {
//   const res = await fetch(
//     `${process.env.API_ROOT}/shops?shopStringId=${shopStringId}`
//   );
//   // The return value is *not* serialized
//   // You can return Date, Map, Set, etc.

//   // Recommendation: handle errors
//   if (!res.ok) {
//     // This will activate the closest `error.js` Error Boundary
//     throw new Error("Failed to fetch data");
//   }

//   return res.json();
// }
// ----------------------------------------------------------------------

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const lgpy = HEADER.DASHBOARD_DESKTOP_HEIGHT + 24;

  // const data = await getData({ shopStringId: params.shopStringId });
  // const shop: Shop = data.data[0];
  return (
    <main>
      {/* <ContainerStyled>{children}</ContainerStyled> */}
      <div>{children}</div>
      {/* <Sidebar /> */}
    </main>
  );
}
